name: graphql_data_loader2
version: 3.0.0
description: Batch and cache database lookups. Works well with GraphQL. Ported from JS.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/graphql_dart/tree/master/graphql_data_loader
environment:
  sdk: '>=2.15.0 <3.0.0'
dev_dependencies:
  graphql_schema2: ^3.0.0
  lints: ^1.0.0
  test: ^1.20.0
dependency_overrides:
  graphql_schema2:
    path: ../graphql_schema
